# Mosquitto Configuration for BRONE
# Jalankan: & "C:\Program Files\mosquitto\mosquitto.exe" -v -c mosquitto_brone.conf

# === Listener 1: Native MQTT (untuk Python publisher) ===
listener 1883
protocol mqtt
allow_anonymous true

# === Listener 2: WebSocket (untuk Browser display) ===
listener 9001
protocol websockets
allow_anonymous true
